/*
 * Shared plumbing for `npm run provision:*`.
 *
 *   - Secrets and generated values live in `.env.local` (gitignored, template in
 *     `.env.example`). Scripts read it, and write generated values back into its
 *     "generated" section, so every run can resume where the last one stopped.
 *   - `--dry-run` performs reads only and prints what it would change.
 *   - Every step reports what it did (✓), what it skipped because it was already done (·), what it
 *     would do in a dry run (○) and what is waiting on a human (⏸).
 *   - v1 resources are on a hard deny list: no script ever reads, changes or deletes them.
 */
import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

import { parseDotenv } from '../lib/proc'

export const ENV_FILE = '.env.local'
/** The Google account that owns the Supabase, Vercel and Resend projects: OWNER_EMAIL in .env.local. */
export const ownerEmail = () => (getValue('OWNER_EMAIL') ?? 'ftcexodius@gmail.com').toLowerCase()
export const GITHUB_REPO = 'AnishYarrakonda/FTC-Pitfund'
export const PRODUCT = 'FTC Pitfund'

/** v1 resources. Provisioning refuses to touch anything that matches (plan §11, prompt 4 §F). */
export const V1_DENY = {
  vercelProjectIds: ['prj_UsUAQbUSY1I0Zj5dG4akTAWtOXtV'],
  vercelProjectNames: ['ftc-sponsorship-portal'],
  // Was the personal team while v1 lived in it. v1 is deleted, so that account is fine to provision into.
  vercelTeamIds: [] as string[],
  supabaseRefs: ['qqizqbtwigyedgskoezm'],
}

export const dryRun = process.argv.includes('--dry-run')

export function flag(name: string) {
  return process.argv.includes(`--${name}`)
}

// ─── Output ────────────────────────────────────────────────────────────────────────────

export const report = {
  done: [] as string[],
  skipped: [] as string[],
  planned: [] as string[],
  waiting: [] as string[],
  warnings: [] as string[],
}

export function heading(text: string) {
  console.log(`\n▸ ${text}`)
}
export function did(text: string) {
  report.done.push(text)
  console.log(`  ✓ ${text}`)
}
export function skip(text: string) {
  report.skipped.push(text)
  console.log(`  · ${text}`)
}
export function plan(text: string) {
  report.planned.push(text)
  console.log(`  ○ would ${text}`)
}
export function waitOn(text: string) {
  report.waiting.push(text)
  console.log(`  ⏸ ${text}`)
}
export function warn(text: string) {
  report.warnings.push(text)
  console.log(`  ⚠ ${text}`)
}
export function info(text: string) {
  console.log(`    ${text}`)
}

export class ProvisionError extends Error {}

export function fail(message: string): never {
  throw new ProvisionError(message)
}

/** Print the run summary and exit: 0 done, 2 waiting on a human, 1 failed. */
export function finish(name: string, error?: unknown): never {
  if (error) {
    console.error(`\n✗ ${name} stopped: ${error instanceof Error ? error.message : String(error)}`)
  }
  console.log(`\n── ${name} summary${dryRun ? ' (dry run: nothing was changed)' : ''}`)
  console.log(`   done ${report.done.length} · already done ${report.skipped.length} · planned ${report.planned.length}`)
  for (const w of report.warnings) console.log(`   ⚠ ${w}`)
  if (report.waiting.length) {
    console.log('\n   Waiting on a human. Do these, then run the same command again:')
    report.waiting.forEach((w, i) => console.log(`   ${i + 1}. ${w}`))
  }
  process.exit(error ? 1 : report.waiting.length ? 2 : 0)
}

// ─── .env.local ────────────────────────────────────────────────────────────────────

let values: Map<string, string> | null = null

function load() {
  if (!values) values = existsSync(ENV_FILE) ? parseDotenv(readFileSync(ENV_FILE, 'utf8')) : new Map()
  return values
}

export function getValue(key: string): string | undefined {
  const v = process.env[key] ?? load().get(key)
  return v === undefined || v.trim() === '' ? undefined : v.trim()
}

export function requireValue(key: string, hint: string): string {
  const v = getValue(key)
  if (!v) fail(`${key} is missing from ${ENV_FILE}. ${hint}`)
  return v
}

/** Store a generated value in .env.local (never in dry runs). Returns the value. */
export function saveValue(key: string, value: string) {
  load().set(key, value)
  if (dryRun) return value
  const text = existsSync(ENV_FILE) ? readFileSync(ENV_FILE, 'utf8') : `# ${PRODUCT} provisioning secrets. Never commit this file.\n`
  const line = `${key}=${value}`
  const pattern = new RegExp(`^\\s*${key}\\s*=.*$`, 'm')
  let next: string
  if (pattern.test(text)) {
    next = text.replace(pattern, line)
  } else {
    const marker = '# ─── Generated by npm run provision (do not edit by hand) ───'
    next = text.includes(marker) ? `${text.replace(/\n?$/, '\n')}${line}\n` : `${text.replace(/\n?$/, '\n')}\n${marker}\n${line}\n`
  }
  writeFileSync(ENV_FILE, next, { mode: 0o600 })
  return value
}

/** A value from .env.local, generated and saved on first use. */
export function generatedValue(key: string, make: () => string) {
  return getValue(key) ?? saveValue(key, make())
}

export const randomHex = (bytes = 24) => randomBytes(bytes).toString('hex')
/** Database passwords: URL-safe, so the connection string needs no escaping. */
export const randomPassword = () => randomBytes(24).toString('base64url').replace(/[-_]/g, 'x')
export const hookSecret = () => `v1,whsec_${randomBytes(32).toString('base64')}`

// ─── Configuration ─────────────────────────────────────────────────────────────────────

export type Stage = 'production' | 'staging'

export function config() {
  const domain = getValue('PITFUND_DOMAIN')?.replace(/^https?:\/\//, '').replace(/\/.*$/, '').toLowerCase()
  return {
    domain,
    siteUrl: domain ? `https://${domain}` : undefined,
    vercelProject: getValue('VERCEL_PROJECT_NAME') ?? 'ftc-pitfund',
    supabaseProjects: {
      production: getValue('SUPABASE_PRODUCTION_PROJECT_NAME') ?? 'ftc-pitfund',
      staging: getValue('SUPABASE_STAGING_PROJECT_NAME') ?? 'ftc-pitfund-staging',
    } satisfies Record<Stage, string>,
    stagingBranch: getValue('STAGING_BRANCH') ?? 'staging',
    adminEmails: (getValue('ADMIN_EMAILS') ?? ownerEmail())
      .split(',')
      .map((e) => e.trim().toLowerCase())
      .filter(Boolean),
    emailFromName: PRODUCT,
  }
}

/** The stable Vercel alias of the staging branch, used by previews for email links and the hook. */
export function stagingSiteUrl(project: string, teamSlug: string, branch: string) {
  return `https://${project}-git-${branch}-${teamSlug}.vercel.app`
}

// ─── HTTP ──────────────────────────────────────────────────────────────────────────────

export type Api = <T = unknown>(method: string, path: string, body?: unknown, opts?: { allow?: number[] }) => Promise<{ status: number; data: T }>

/** A small JSON client. Mutating calls are refused in dry runs (callers check `dryRun` first). */
export function apiClient(base: string, headers: Record<string, string>, label: string): Api {
  return async (method, path, body, opts) => {
    if (dryRun && method !== 'GET') throw new Error(`BUG: ${label} ${method} ${path} attempted during a dry run`)
    let res: Response
    try {
      res = await fetch(`${base}${path}`, {
        method,
        headers: { 'Content-Type': 'application/json', ...headers },
        body: body === undefined ? undefined : JSON.stringify(body),
        signal: AbortSignal.timeout(60_000),
      })
    } catch (e) {
      fail(`Couldn't reach ${label} (${method} ${path}): ${e instanceof Error ? e.message : e}`)
    }
    const text = await res.text()
    let data: unknown = text
    try {
      data = text ? JSON.parse(text) : null
    } catch {
      // keep text
    }
    if (!res.ok && !opts?.allow?.includes(res.status)) {
      const detail = typeof data === 'string' ? data.slice(0, 300) : JSON.stringify(data).slice(0, 300)
      fail(`${label} ${method} ${path} → ${res.status}: ${detail}`)
    }
    return { status: res.status, data: data as never }
  }
}

export function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms))
}
