/*
 * npm run setup — everything a fresh clone needs, with Docker as the only prerequisite.
 *
 *   1. Check Docker is running.
 *   2. Write supabase/.env (hook secret, Google toggle) and start the local Supabase stack.
 *   3. Merge local values into .env.local. Existing non-local values are never overwritten.
 *   4. Apply migrations.
 *   5. Seed the `demo` scenario (pass --scenario to choose another, --no-seed to skip).
 */
import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

import { argValue, isLocalHost } from './lib/env'
import { parseDotenv, run, runInherit, runScript, supabaseBin } from './lib/proc'

const ENV_FILE = '.env.local'
const SUPABASE_ENV_FILE = 'supabase/.env'

function step(message: string) {
  console.log(`\n▸ ${message}`)
}

function fail(message: string): never {
  console.error(`\n✗ ${message}`)
  process.exit(1)
}

function checkDocker() {
  step('Checking Docker')
  const docker = run('docker', ['info', '--format', '{{.ServerVersion}}'])
  if (docker.code !== 0) {
    fail(
      docker.stderr.includes('command not found') || docker.stderr.includes('ENOENT')
        ? 'Docker is not installed. Install Docker Desktop (https://www.docker.com/products/docker-desktop), start it, then run `npm run setup` again.'
        : "Docker isn't running. Start Docker Desktop, wait until it says it's running, then run `npm run setup` again.",
    )
  }
  console.log(`  Docker ${docker.stdout.trim()}`)
}

function readEnvFile(path: string) {
  return existsSync(path) ? parseDotenv(readFileSync(path, 'utf8')) : new Map<string, string>()
}

function writeSupabaseEnv(existing: Map<string, string>): boolean {
  const current = readEnvFile(SUPABASE_ENV_FILE)
  const secret =
    existing.get('SEND_EMAIL_HOOK_SECRET') ||
    current.get('SEND_EMAIL_HOOK_SECRET') ||
    `v1,whsec_${randomBytes(32).toString('base64')}`
  const googleId = existing.get('GOOGLE_CLIENT_ID') ?? ''
  const googleSecret = existing.get('GOOGLE_CLIENT_SECRET') ?? ''
  const next = new Map([
    ['SEND_EMAIL_HOOK_SECRET', secret],
    ['SUPABASE_AUTH_EXTERNAL_GOOGLE_ENABLED', googleId && googleSecret ? 'true' : 'false'],
    ['SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID', googleId],
    ['SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET', googleSecret],
  ])
  const changed = [...next].some(([k, v]) => current.get(k) !== v)
  if (changed) {
    writeFileSync(
      SUPABASE_ENV_FILE,
      '# Generated by `npm run setup` for the local Supabase stack. Do not commit.\n' +
        [...next].map(([k, v]) => `${k}=${v}`).join('\n') +
        '\n',
    )
  }
  return changed
}

async function startSupabase(configChanged: boolean) {
  step('Starting the local Supabase stack')
  const bin = supabaseBin()
  const status = run(bin, ['status', '-o', 'env'])
  const running = status.code === 0 && status.stdout.includes('API_URL')
  if (running && configChanged) {
    console.log('  Auth settings changed; restarting the stack')
    await runInherit(bin, ['stop'])
  }
  if (!running || configChanged) {
    const code = await runInherit(bin, ['start'])
    if (code !== 0) fail('`supabase start` failed. Check the output above (Docker memory is the usual cause).')
  } else {
    console.log('  Already running')
  }
  const env = run(bin, ['status', '-o', 'env'])
  if (env.code !== 0) fail(`Couldn't read the local stack status:\n${env.stderr}`)
  return parseDotenv(env.stdout)
}

function mergeEnvLocal(existing: Map<string, string>, stack: Map<string, string>, hookSecret: string) {
  step(`Writing ${ENV_FILE}`)
  const apiUrl = stack.get('API_URL') ?? 'http://127.0.0.1:54321'
  const dbUrl = stack.get('DB_URL') ?? 'postgresql://postgres:postgres@127.0.0.1:54322/postgres'
  const smtpPort = '54325'

  const changes: string[] = []
  const kept: string[] = []
  const values = new Map(existing)

  const set = (key: string, value: string, { onlyIfMissing = false, local = true } = {}) => {
    const current = existing.get(key)
    if (current === value) return
    if (current !== undefined && current !== '' && (onlyIfMissing || !local)) {
      if (!local) kept.push(key)
      return
    }
    values.set(key, value)
    changes.push(current === undefined || current === '' ? `+ ${key}` : `~ ${key}`)
  }

  const supabaseIsLocal = !existing.get('NEXT_PUBLIC_SUPABASE_URL') || isLocalHost(existing.get('NEXT_PUBLIC_SUPABASE_URL')!)
  const dbIsLocal = !existing.get('DATABASE_URL') || isLocalHost(existing.get('DATABASE_URL')!)

  set('NEXT_PUBLIC_SITE_URL', 'http://127.0.0.1:3000', { onlyIfMissing: true })
  set('NEXT_PUBLIC_SUPABASE_URL', apiUrl, { local: supabaseIsLocal })
  set('NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY', stack.get('PUBLISHABLE_KEY') ?? stack.get('ANON_KEY') ?? '', { local: supabaseIsLocal })
  set('SUPABASE_SECRET_KEY', stack.get('SECRET_KEY') ?? stack.get('SERVICE_ROLE_KEY') ?? '', { local: supabaseIsLocal })
  set('DATABASE_URL', dbUrl, { local: dbIsLocal })
  set('SEND_EMAIL_HOOK_SECRET', hookSecret, { local: supabaseIsLocal })
  set('EMAIL_TRANSPORT', 'smtp', { onlyIfMissing: true })
  set('EMAIL_FROM', 'FTC Pitfund <noreply@pitfund.test>', { onlyIfMissing: true })
  set('SMTP_URL', `smtp://127.0.0.1:${smtpPort}`, { onlyIfMissing: true })
  set('MAILPIT_URL', stack.get('MAILPIT_URL') ?? 'http://127.0.0.1:54324', { onlyIfMissing: true })
  set('CRON_SECRET', randomBytes(24).toString('hex'), { onlyIfMissing: true })
  const googleReady = Boolean(existing.get('GOOGLE_CLIENT_ID') && existing.get('GOOGLE_CLIENT_SECRET'))
  set('NEXT_PUBLIC_GOOGLE_AUTH_ENABLED', googleReady ? 'true' : 'false', { local: true })

  if (changes.length === 0) {
    console.log('  Up to date')
  } else {
    const header = existsSync(ENV_FILE)
      ? ''
      : '# Local development environment. Generated and merged by `npm run setup`.\n# See .env.example for every variable.\n'
    const original = existsSync(ENV_FILE) ? readFileSync(ENV_FILE, 'utf8') : header
    let text = original
    for (const [key, value] of values) {
      if (existing.get(key) === value) continue
      const line = `${key}=${value}`
      const pattern = new RegExp(`^\\s*${key}\\s*=.*$`, 'm')
      text = pattern.test(text) ? text.replace(pattern, line) : `${text.replace(/\n?$/, '\n')}${line}\n`
    }
    writeFileSync(ENV_FILE, text)
    for (const c of changes) console.log(`  ${c}`)
  }
  if (kept.length) {
    fail(
      `${ENV_FILE} points ${kept.join(', ')} at a non-local project, and setup never overwrites those.\n` +
        '  Setup, migrations and seeds only run against the local stack. Move the remote values to\n' +
        '  a different file (for example .env.production.local), then run `npm run setup` again.',
    )
  }
  return values
}

async function main() {
  checkDocker()

  const existing = readEnvFile(ENV_FILE)
  const configChanged = writeSupabaseEnv(existing)
  const hookSecret = readEnvFile(SUPABASE_ENV_FILE).get('SEND_EMAIL_HOOK_SECRET')!

  const stack = await startSupabase(configChanged)
  const env = mergeEnvLocal(existing, stack, hookSecret)
  const childEnv = { ...process.env, ...Object.fromEntries(env) }

  step('Applying migrations')
  if ((await runScript('scripts/db-migrate.ts', [], childEnv)) !== 0) fail('Migrations failed.')

  if (!process.argv.includes('--no-seed')) {
    const scenario = argValue('scenario') ?? 'demo'
    step(`Seeding the "${scenario}" scenario`)
    if ((await runScript('scripts/seed/index.ts', ['--scenario', scenario], childEnv)) !== 0) fail('Seeding failed.')
  }

  console.log(
    '\n✓ Ready.\n\n' +
      '  npm run dev          http://127.0.0.1:3000\n' +
      '  Personas             http://127.0.0.1:3000/dev\n' +
      '  Component gallery    http://127.0.0.1:3000/dev/ui\n' +
      `  Local email          ${env.get('MAILPIT_URL')}\n` +
      '  Database studio      http://127.0.0.1:54323\n',
  )
}

main().catch((e) => fail(e instanceof Error ? e.message : String(e)))
